# ASIGNMENT #1

In [2]:
import pandas as pd
dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':str, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}
House_Data=pd.read_csv('kc_house_data.csv', sep=',',dtype=dtype_dict)
House_Train_Data=pd.read_csv('kc_house_train_data.csv', sep=',', dtype=dtype_dict)
House_Test_Data=pd.read_csv('kc_house_test_data.csv',sep=',',dtype=dtype_dict)
House_Data

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0       3.0       1.00   
1      6414100192  20141209T000000  538000.0       3.0       2.25   
2      5631500400  20150225T000000  180000.0       2.0       1.00   
3      2487200875  20141209T000000  604000.0       4.0       3.00   
4      1954400510  20150218T000000  510000.0       3.0       2.00   
...           ...              ...       ...       ...        ...   
21608  0263000018  20140521T000000  360000.0       3.0       2.50   
21609  6600060120  20150223T000000  400000.0       4.0       2.50   
21610  1523300141  20140623T000000  402101.0       2.0       0.75   
21611  0291310100  20150116T000000  400000.0       3.0       2.50   
21612  1523300157  20141015T000000  325000.0       2.0       0.75   

       sqft_living  sqft_lot floors  waterfront  view  ...  grade  sqft_above  \
0           1180.0      5650      1           0     0  ...      7        1180   
1           2570.0      7242      2           0     0  ...      7        2170   
2            770.0     10000      1           0     0  ...      6         770   
3           1960.0      5000      1           0     0  ...      7        1050   
4           1680.0      8080      1           0     0  ...      8        1680   
...            ...       ...    ...         ...   ...  ...    ...         ...   
21608       1530.0      1131      3           0     0  ...      8        1530   
21609       2310.0      5813      2           0     0  ...      8        2310   
21610       1020.0      1350      2           0     0  ...      7        1020   
21611       1600.0      2388      2           0     0  ...      8        1600   
21612       1020.0      1076      2           0     0  ...      7        1020   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0                  0      1955             0    98178  47.5112 -122.257   
1                400      1951          1991    98125  47.7210 -122.319   
2                  0      1933             0    98028  47.7379 -122.233   
3                910      1965             0    98136  47.5208 -122.393   
4                  0      1987             0    98074  47.6168 -122.045   
...              ...       ...           ...      ...      ...      ...   
21608              0      2009             0    98103  47.6993 -122.346   
21609              0      2014             0    98146  47.5107 -122.362   
21610              0      2009             0    98144  47.5944 -122.299   
21611              0      2004             0    98027  47.5345 -122.069   
21612              0      2008             0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15  
0             1340.0      5650.0  
1             1690.0      7639.0  
2             2720.0      8062.0  
3             1360.0      5000.0  
4             1800.0      7503.0  
...              ...         ...  
21608         1530.0      1509.0  
21609         1830.0      7200.0  
21610         1020.0      2007.0  
21611         1410.0      1287.0  
21612         1020.0      1357.0  

[21613 rows x 21 columns]

## Adding Data

In [16]:
import math
def sq(Data):
    return Data*Data
House_Data['bedrooms_sq']=House_Data['bedrooms'].apply(sq)
House_Test_Data['bedrooms_sq']=House_Test_Data['bedrooms'].apply(sq)
House_Train_Data['bedrooms_sq']=House_Train_Data['bedrooms'].apply(sq)
House_Test_Data

id             date      price  bedrooms  bathrooms  \
0     0114101516  20140528T000000   310000.0       3.0       1.00   
1     9297300055  20150124T000000   650000.0       4.0       3.00   
2     1202000200  20141103T000000   233000.0       3.0       2.00   
3     8562750320  20141110T000000   580500.0       3.0       2.50   
4     7589200193  20141110T000000   535000.0       3.0       1.00   
...          ...              ...        ...       ...        ...   
4224  8672200110  20150317T000000  1088000.0       5.0       3.75   
4225  5087900040  20141017T000000   350000.0       4.0       2.75   
4226  3448900210  20141014T000000   610685.0       4.0       2.50   
4227  6600060120  20150223T000000   400000.0       4.0       2.50   
4228  1523300141  20140623T000000   402101.0       2.0       0.75   

      sqft_living  sqft_lot floors  waterfront  view  ...  yr_renovated  \
0          1430.0     19901    1.5           0     0  ...             0   
1          2950.0      5000      2           0     3  ...             0   
2          1710.0      4697    1.5           0     0  ...             0   
3          2320.0      3980      2           0     0  ...             0   
4          1090.0      3000    1.5           0     0  ...             0   
...           ...       ...    ...         ...   ...  ...           ...   
4224       4170.0      8142      2           0     2  ...             0   
4225       2500.0      5995      2           0     0  ...             0   
4226       2520.0      6023      2           0     0  ...             0   
4227       2310.0      5813      2           0     0  ...             0   
4228       1020.0      1350      2           0     0  ...             0   

      zipcode      lat     long  sqft_living15  sqft_lot15 bedrooms_sq  \
0       98028  47.7558 -122.229         1780.0     12697.0         9.0   
1       98126  47.5714 -122.375         2140.0      4000.0        16.0   
2       98002  47.3048 -122.218         1030.0      4705.0         9.0   
3       98027  47.5391 -122.070         2580.0      3980.0         9.0   
4       98117  47.6889 -122.375         1570.0      5080.0         9.0   
...       ...      ...      ...            ...         ...         ...   
4224    98056  47.5354 -122.181         3030.0      7980.0        25.0   
4225    98042  47.3749 -122.107         2530.0      5988.0        16.0   
4226    98056  47.5137 -122.167         2520.0      6023.0        16.0   
4227    98146  47.5107 -122.362         1830.0      7200.0        16.0   
4228    98144  47.5944 -122.299         1020.0      2007.0         4.0   

      bed_bath_rooms  Log_Sqft_Living  Lat_Plus_Long  
0               3.00         7.265430       -74.4732  
1              12.00         7.989560       -74.8036  
2               6.00         7.444249       -74.9132  
3               7.50         7.749322       -74.5309  
4               3.00         6.993933       -74.6861  
...              ...              ...            ...  
4224           18.75         8.335671       -74.6456  
4225           11.00         7.824046       -74.7321  
4226           10.00         7.832014       -74.6533  
4227           10.00         7.745003       -74.8513  
4228            1.50         6.927558       -74.7046  

[4229 rows x 25 columns]

In [17]:
House_Data['bed_bath_rooms']=House_Data['bedrooms']*House_Data['bathrooms']
House_Test_Data['bed_bath_rooms']=House_Test_Data['bedrooms']*House_Test_Data['bathrooms']
House_Train_Data['bed_bath_rooms']=House_Train_Data['bedrooms']*House_Train_Data['bathrooms']
House_Train_Data

id             date      price  bedrooms  bathrooms  \
0      7129300520  20141013T000000   221900.0       3.0       1.00   
1      6414100192  20141209T000000   538000.0       3.0       2.25   
2      5631500400  20150225T000000   180000.0       2.0       1.00   
3      2487200875  20141209T000000   604000.0       4.0       3.00   
4      1954400510  20150218T000000   510000.0       3.0       2.00   
...           ...              ...        ...       ...        ...   
17379  7936000429  20150326T000000  1007500.0       4.0       3.50   
17380  2997800021  20150219T000000   475000.0       3.0       2.50   
17381  0263000018  20140521T000000   360000.0       3.0       2.50   
17382  0291310100  20150116T000000   400000.0       3.0       2.50   
17383  1523300157  20141015T000000   325000.0       2.0       0.75   

       sqft_living  sqft_lot floors  waterfront  view  ...  yr_renovated  \
0           1180.0      5650      1           0     0  ...             0   
1           2570.0      7242      2           0     0  ...          1991   
2            770.0     10000      1           0     0  ...             0   
3           1960.0      5000      1           0     0  ...             0   
4           1680.0      8080      1           0     0  ...             0   
...            ...       ...    ...         ...   ...  ...           ...   
17379       3510.0      7200      2           0     0  ...             0   
17380       1310.0      1294      2           0     0  ...             0   
17381       1530.0      1131      3           0     0  ...             0   
17382       1600.0      2388      2           0     0  ...             0   
17383       1020.0      1076      2           0     0  ...             0   

       zipcode      lat     long  sqft_living15  sqft_lot15 bedrooms_sq  \
0        98178  47.5112 -122.257         1340.0      5650.0         9.0   
1        98125  47.7210 -122.319         1690.0      7639.0         9.0   
2        98028  47.7379 -122.233         2720.0      8062.0         4.0   
3        98136  47.5208 -122.393         1360.0      5000.0        16.0   
4        98074  47.6168 -122.045         1800.0      7503.0         9.0   
...        ...      ...      ...            ...         ...         ...   
17379    98136  47.5537 -122.398         2050.0      6200.0        16.0   
17380    98116  47.5773 -122.409         1330.0      1265.0         9.0   
17381    98103  47.6993 -122.346         1530.0      1509.0         9.0   
17382    98027  47.5345 -122.069         1410.0      1287.0         9.0   
17383    98144  47.5941 -122.299         1020.0      1357.0         4.0   

       bed_bath_rooms  Log_Sqft_Living  Lat_Plus_Long  
0                3.00         7.073270       -74.7458  
1                6.75         7.851661       -74.5980  
2                2.00         6.646391       -74.4951  
3               12.00         7.580700       -74.8722  
4                6.00         7.426549       -74.4282  
...               ...              ...            ...  
17379           14.00         8.163371       -74.8443  
17380            7.50         7.177782       -74.8317  
17381            7.50         7.333023       -74.6467  
17382            7.50         7.377759       -74.5345  
17383            1.50         6.927558       -74.7049  

[17384 rows x 25 columns]

In [18]:
House_Data['Log_Sqft_Living']=House_Data['sqft_living'].apply(math.log)
House_Test_Data['Log_Sqft_Living']=House_Test_Data['sqft_living'].apply(math.log)
House_Train_Data['Log_Sqft_Living']=House_Train_Data['sqft_living'].apply(math.log)
House_Test_Data

id             date      price  bedrooms  bathrooms  \
0     0114101516  20140528T000000   310000.0       3.0       1.00   
1     9297300055  20150124T000000   650000.0       4.0       3.00   
2     1202000200  20141103T000000   233000.0       3.0       2.00   
3     8562750320  20141110T000000   580500.0       3.0       2.50   
4     7589200193  20141110T000000   535000.0       3.0       1.00   
...          ...              ...        ...       ...        ...   
4224  8672200110  20150317T000000  1088000.0       5.0       3.75   
4225  5087900040  20141017T000000   350000.0       4.0       2.75   
4226  3448900210  20141014T000000   610685.0       4.0       2.50   
4227  6600060120  20150223T000000   400000.0       4.0       2.50   
4228  1523300141  20140623T000000   402101.0       2.0       0.75   

      sqft_living  sqft_lot floors  waterfront  view  ...  yr_renovated  \
0          1430.0     19901    1.5           0     0  ...             0   
1          2950.0      5000      2           0     3  ...             0   
2          1710.0      4697    1.5           0     0  ...             0   
3          2320.0      3980      2           0     0  ...             0   
4          1090.0      3000    1.5           0     0  ...             0   
...           ...       ...    ...         ...   ...  ...           ...   
4224       4170.0      8142      2           0     2  ...             0   
4225       2500.0      5995      2           0     0  ...             0   
4226       2520.0      6023      2           0     0  ...             0   
4227       2310.0      5813      2           0     0  ...             0   
4228       1020.0      1350      2           0     0  ...             0   

      zipcode      lat     long  sqft_living15  sqft_lot15 bedrooms_sq  \
0       98028  47.7558 -122.229         1780.0     12697.0         9.0   
1       98126  47.5714 -122.375         2140.0      4000.0        16.0   
2       98002  47.3048 -122.218         1030.0      4705.0         9.0   
3       98027  47.5391 -122.070         2580.0      3980.0         9.0   
4       98117  47.6889 -122.375         1570.0      5080.0         9.0   
...       ...      ...      ...            ...         ...         ...   
4224    98056  47.5354 -122.181         3030.0      7980.0        25.0   
4225    98042  47.3749 -122.107         2530.0      5988.0        16.0   
4226    98056  47.5137 -122.167         2520.0      6023.0        16.0   
4227    98146  47.5107 -122.362         1830.0      7200.0        16.0   
4228    98144  47.5944 -122.299         1020.0      2007.0         4.0   

      bed_bath_rooms  Log_Sqft_Living  Lat_Plus_Long  
0               3.00         7.265430       -74.4732  
1              12.00         7.989560       -74.8036  
2               6.00         7.444249       -74.9132  
3               7.50         7.749322       -74.5309  
4               3.00         6.993933       -74.6861  
...              ...              ...            ...  
4224           18.75         8.335671       -74.6456  
4225           11.00         7.824046       -74.7321  
4226           10.00         7.832014       -74.6533  
4227           10.00         7.745003       -74.8513  
4228            1.50         6.927558       -74.7046  

[4229 rows x 25 columns]

In [19]:
House_Data['Lat_Plus_Long']=House_Data['lat']+House_Data['long']
House_Test_Data['Lat_Plus_Long']=House_Test_Data['lat']+House_Test_Data['long']
House_Train_Data['Lat_Plus_Long']=House_Train_Data['lat']+House_Train_Data['long']
House_Test_Data

id             date      price  bedrooms  bathrooms  \
0     0114101516  20140528T000000   310000.0       3.0       1.00   
1     9297300055  20150124T000000   650000.0       4.0       3.00   
2     1202000200  20141103T000000   233000.0       3.0       2.00   
3     8562750320  20141110T000000   580500.0       3.0       2.50   
4     7589200193  20141110T000000   535000.0       3.0       1.00   
...          ...              ...        ...       ...        ...   
4224  8672200110  20150317T000000  1088000.0       5.0       3.75   
4225  5087900040  20141017T000000   350000.0       4.0       2.75   
4226  3448900210  20141014T000000   610685.0       4.0       2.50   
4227  6600060120  20150223T000000   400000.0       4.0       2.50   
4228  1523300141  20140623T000000   402101.0       2.0       0.75   

      sqft_living  sqft_lot floors  waterfront  view  ...  yr_renovated  \
0          1430.0     19901    1.5           0     0  ...             0   
1          2950.0      5000      2           0     3  ...             0   
2          1710.0      4697    1.5           0     0  ...             0   
3          2320.0      3980      2           0     0  ...             0   
4          1090.0      3000    1.5           0     0  ...             0   
...           ...       ...    ...         ...   ...  ...           ...   
4224       4170.0      8142      2           0     2  ...             0   
4225       2500.0      5995      2           0     0  ...             0   
4226       2520.0      6023      2           0     0  ...             0   
4227       2310.0      5813      2           0     0  ...             0   
4228       1020.0      1350      2           0     0  ...             0   

      zipcode      lat     long  sqft_living15  sqft_lot15 bedrooms_sq  \
0       98028  47.7558 -122.229         1780.0     12697.0         9.0   
1       98126  47.5714 -122.375         2140.0      4000.0        16.0   
2       98002  47.3048 -122.218         1030.0      4705.0         9.0   
3       98027  47.5391 -122.070         2580.0      3980.0         9.0   
4       98117  47.6889 -122.375         1570.0      5080.0         9.0   
...       ...      ...      ...            ...         ...         ...   
4224    98056  47.5354 -122.181         3030.0      7980.0        25.0   
4225    98042  47.3749 -122.107         2530.0      5988.0        16.0   
4226    98056  47.5137 -122.167         2520.0      6023.0        16.0   
4227    98146  47.5107 -122.362         1830.0      7200.0        16.0   
4228    98144  47.5944 -122.299         1020.0      2007.0         4.0   

      bed_bath_rooms  Log_Sqft_Living  Lat_Plus_Long  
0               3.00         7.265430       -74.4732  
1              12.00         7.989560       -74.8036  
2               6.00         7.444249       -74.9132  
3               7.50         7.749322       -74.5309  
4               3.00         6.993933       -74.6861  
...              ...              ...            ...  
4224           18.75         8.335671       -74.6456  
4225           11.00         7.824046       -74.7321  
4226           10.00         7.832014       -74.6533  
4227           10.00         7.745003       -74.8513  
4228            1.50         6.927558       -74.7046  

[4229 rows x 25 columns]

## Calculating the Mean of the Added Data

In [12]:
print('The mean of Sq. Bedrooms: {}'.format(House_Test_Data['bedrooms_sq'].mean()))
print('The mean of bed * bath: {}'.format(House_Test_Data['bed_bath_rooms'].mean()))
print('The mean of the log of sqft: {}'.format(House_Test_Data['Log_Sqft_Living'].mean()))
print('The mean of Lat + Long: {}'.format(House_Test_Data['Lat_Plus_Long'].mean()))

The mean of Sq. Bedrooms: 12.4466777015843
The mean of bed * bath: 7.5039016315913925
The mean of the log of sqft: 7.550274679645921
The mean of Lat + Long: -74.65333355403185


## Separating the Features for the Models

In [30]:
ft1=['sqft_living','bedrooms','bathrooms','lat','long']
ft2=['sqft_living','bedrooms','bathrooms','lat','long','bed_bath_rooms']
ft3=['sqft_living','bedrooms','bathrooms','lat','long','bed_bath_rooms','bedrooms_sq','Log_Sqft_Living','Lat_Plus_Long']
x1=House_Data[ft1]
x2=House_Data[ft2]
x3=House_Data[ft3]
y=House_Data['price']
x1_train=House_Train_Data[ft1]
x2_train=House_Train_Data[ft2]
x3_train=House_Train_Data[ft3]
y_train=House_Train_Data['price']
x1_test=House_Test_Data[ft1]
x2_test=House_Test_Data[ft2]
x3_test=House_Test_Data[ft3]
y_test=House_Test_Data['price']

## Applying Models and Finding Coefficients

In [21]:
from sklearn.linear_model import LinearRegression
Model1=LinearRegression()
Model1.fit(x1_train,y_train)
coef_1=pd.DataFrame(Model1.coef_, x1.columns, columns=['Coefficient'])
coef_1

Coefficient
sqft_living     312.258646
bedrooms     -59586.533154
bathrooms     15706.742083
lat          658619.263931
long        -309374.351268

In [24]:
Model2=LinearRegression()
Model2.fit(x2_train,y_train)
coef_2=pd.DataFrame(Model2.coef_,x2.columns,columns=['Coefficient'])
coef_2

Coefficient
sqft_living        306.610053
bedrooms       -113446.368070
bathrooms       -71461.308293
lat             654844.629503
long           -294298.969138
bed_bath_rooms   25579.652001

In [26]:
Model3=LinearRegression()
Model3.fit(x3_train,y_train)
coef_3=pd.DataFrame(Model3.coef_,x3.columns,columns=['Coefficient'])
coef_3

Coefficient
sqft_living         529.422820
bedrooms          34514.229578
bathrooms         67060.781319
lat              534085.610867
long            -406750.710861
bed_bath_rooms    -8570.504395
bedrooms_sq       -6788.586670
Log_Sqft_Living -561831.484076
Lat_Plus_Long    127334.900006

## ROOT SUM OF SQUARES TRAIN

In [29]:
RSS1_train=((Model1.predict(x1_train)-y_train)**2).sum()
RSS2_train=((Model2.predict(x2_train)-y_train)**2).sum()
RSS3_train=((Model3.predict(x3_train)-y_train)**2).sum()
print('RSS1: {}'.format(RSS1_train))
print('RSS2: {}'.format(RSS2_train))
print('RSS3: {}'.format(RSS3_train))

RSS1: 967879963049545.8
RSS2: 958419635074070.0
RSS3: 903436455050479.2


## ROOT SUM OF SQUARES TEST

In [31]:
RSS1_test=((Model1.predict(x1_test)-y_test)**2).sum()
RSS2_test=((Model2.predict(x2_test)-y_test)**2).sum()
RSS3_test=((Model3.predict(x3_test)-y_test)**2).sum()
print('RSS1: {}'.format(RSS1_test))
print('RSS2: {}'.format(RSS2_test))
print('RSS3: {}'.format(RSS3_test))

RSS1: 225500469795490.34
RSS2: 223377462976467.5
RSS3: 259236319207179.94


# ASSIGNMENT #2

## Converting to a Numpy

In [48]:
import numpy as np
def get_numpy_data(dataframe, features, output):
    dataframe['constant'] = 1 # add a constant column to a DataFrame
    # prepend variable 'constant' to the features list
    features = ['constant'] + features
    # select the columns of DataFrame given by the ‘features’ list into the DataFrame ‘features_Dataframe’
    features_Dataframe=dataframe[features]
    # this will convert the features_sframe into a numpy matrix:
    features_matrix = features_Dataframe.to_numpy()
    # assign the column of data_sframe associated with the target to the variable ‘output_sarray’
    output_darray = dataframe[output]
    # this will convert the SArray into a numpy array:
    output_array = output_darray.to_numpy()
    return(features_matrix, output_array)

In [49]:
(example_features, example_output) = get_numpy_data(House_Data, ['sqft_living'], 'price')
print(example_features)
print(example_output)
print(type(example_features))

[[1.00e+00 1.18e+03]
 [1.00e+00 2.57e+03]
 [1.00e+00 7.70e+02]
 ...
 [1.00e+00 1.02e+03]
 [1.00e+00 1.60e+03]
 [1.00e+00 1.02e+03]]
[221900. 538000. 180000. ... 402101. 400000. 325000.]
<class 'numpy.ndarray'>


## Predicting Output Given The Regression Weights

In [50]:
def predict_output(feature_matrix, weights):
    predictions = np.dot(feature_matrix, weights)
    return(predictions)
weigths=np.array([1,1])
test_predictions = predict_output(example_features, weights)
print(test_predictions[0])
print(test_predictions[1])

1181.0
2571.0


## Calculating the Derivative

In [54]:
def feature_derivative(errors, feature):
    derivative = 2*np.dot(errors, feature)
    return(derivative)
errors=test_predictions-example_output
features=example_features
derivative=feature_derivative(errors,features)
print(derivative)

[-2.32559010e+10 -5.85652694e+13]


In [55]:
print(example_output)
print(errors)
print(features)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
[-220719. -535429. -179229. ... -401080. -398399. -323979.]
[[1.00e+00 1.18e+03]
 [1.00e+00 2.57e+03]
 [1.00e+00 7.70e+02]
 ...
 [1.00e+00 1.02e+03]
 [1.00e+00 1.60e+03]
 [1.00e+00 1.02e+03]]


## Gradient Descent

In [60]:
def gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False 
    weights = np.array(initial_weights)
    while not converged:
        predictions = predict_output(feature_matrix, weights)
        errors = predictions - output
        gradient_sum_squares = 0
        for i in range(len(weights)): 
            derivative = feature_derivative(errors, feature_matrix[:, i])
            gradient_sum_squares += (derivative**2)
            weights[i] -= (step_size * derivative)
        gradient_magnitude = math.sqrt(gradient_sum_squares)
        if gradient_magnitude < tolerance:
            converged = True
    return(weights)

### Using the Train Data

In [64]:
simple_features = ['sqft_living']
output = 'price'
(simple_feature_matrix, train_output) = get_numpy_data(House_Train_Data, simple_features, output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

In [66]:
test_weight = gradient_descent(simple_feature_matrix, train_output, initial_weights, step_size, tolerance)
print(test_weight)

[-46999.88716555    281.91211918]


### Using the Test Data

In [67]:
(test_simple_feature_matrix, test_output) = get_numpy_data(House_Test_Data, simple_features, output)
test_predictions = predict_output(test_simple_feature_matrix, test_weight)
print(test_predictions)

[356134.443255   784640.86440132 435069.83662406 ... 663418.65315598
 604217.10812919 240550.47439317]


In [68]:
test_predictions[0]

356134.4432550024

In [69]:
test_residuals = test_output - test_predictions
test_RSS = (test_residuals * test_residuals).sum()
test_RSS

275400044902128.3

## Running Multiple Regression

### Train Data

In [71]:
model_features = ['sqft_living', 'sqft_living15']
my_output = 'price'
(feature_matrix, output) = get_numpy_data(House_Train_Data, model_features, my_output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12
tolerance = 1e9

In [72]:
weight_2 = gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance)
weight_2

array([-9.99999688e+04,  2.45072603e+02,  6.52795267e+01])

### Test Data

In [74]:
(test_feature_matrix, test_output) = get_numpy_data(House_Test_Data, model_features, my_output)

test_predictions_2 = predict_output(test_feature_matrix, weight_2)
test_predictions_2

array([366651.41162949, 762662.39850726, 386312.09557541, ...,
       682087.39916306, 585579.27901327, 216559.20391786])

In [75]:
test_predictions_2[0]

366651.4116294939

In [77]:
House_Test_Data['price'][0]

310000.0

In [78]:
test_residuals_2 = test_output - test_predictions_2
test_RSS_2 = (test_residuals_2**2).sum()
test_RSS_2

270263443629803.56